# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connexion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from tools import *
from homeUI import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_connexion(object):
    def setupUi(self, connexion):
        print("========================OUVERTURE CONNEXION.UI========================")
        connexion.setObjectName("connexion")
        connexion.resize(300, 500)
        connexion.setMinimumSize(QtCore.QSize(300, 500))
        connexion.setMaximumSize(QtCore.QSize(300, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 84, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 84, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        connexion.setPalette(palette)
        connexion.setStyleSheet("background-color: #23272A  ;")
        self.centralwidget = QtWidgets.QWidget(connexion)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 4, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_login)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_password_login = QtWidgets.QFrame(self.page_login)
        self.line_password_login.setStyleSheet("border: 2px solid #404EED ;")
        self.line_password_login.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_password_login.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_password_login.setObjectName("line_password_login")
        self.gridLayout.addWidget(self.line_password_login, 7, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_title = QtWidgets.QLabel(self.page_login)
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color:#EEEEEE;\n"
"font: 30pt \"Bebas Neue\";\n"
"background:#23272A;\n"
"selection-background-color: darkgray;\n"
"")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 1, 1, 1, 1)
        self.lineEdit_password_login = QtWidgets.QLineEdit(self.page_login)
        self.lineEdit_password_login.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lineEdit_password_login.setPalette(palette)
        self.lineEdit_password_login.setStyleSheet("color:#EEEEEE;\n"
"font: 15pt \"Verdana\";\n"
" border: None;\n"
"border-bottom-color: white;\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"background:#23272A;\n"
"selection-background-color: darkgray;\n"
"")
        self.lineEdit_password_login.setInputMask("")
        self.lineEdit_password_login.setText("")
        self.lineEdit_password_login.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_login.setObjectName("lineEdit_password_login")
        self.gridLayout.addWidget(self.lineEdit_password_login, 6, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 10, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 2, 1, 1)
        self.lineEdit_username_login = QtWidgets.QLineEdit(self.page_login)
        self.lineEdit_username_login.setMinimumSize(QtCore.QSize(160, 40))
        self.lineEdit_username_login.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_username_login.setStyleSheet("color:#EEEEEE;\n"
"font: 15pt \"Verdana\";\n"
" border: None;\n"
"border-bottom-color: white;\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"background:#23272A;\n"
"selection-background-color: darkgray;\n"
"")
        self.lineEdit_username_login.setObjectName("lineEdit_username_login")
        self.gridLayout.addWidget(self.lineEdit_username_login, 2, 1, 1, 1)
        self.pushButton_login = QtWidgets.QPushButton(self.page_login)
        self.pushButton_login.setStyleSheet("QPushButton\n"
"{\n"
"    color: #EEEEEE;\n"
"    font: 17pt \"Verdana\";\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"    background-color:#2C2F33;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#50555C;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color:#625C6A;\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.gridLayout.addWidget(self.pushButton_login, 11, 1, 1, 1)
        self.pushButton_createAccount = QtWidgets.QPushButton(self.page_login)
        self.pushButton_createAccount.setMaximumSize(QtCore.QSize(16777215, 45))
        self.pushButton_createAccount.setStyleSheet("QPushButton\n"
"{\n"
"    color: #EEEEEE;\n"
"    font: 8pt \"Verdana\";\n"
"    text-decoration: underline;\n"
"    text-align:center;\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"    background-color:#23272A;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: #6671F0;\n"
"}")
        self.pushButton_createAccount.setObjectName("pushButton_createAccount")
        self.gridLayout.addWidget(self.pushButton_createAccount, 12, 1, 1, 1)
        self.label_event_login = QtWidgets.QLabel(self.page_login)
        self.label_event_login.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_event_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_event_login.setStyleSheet("color:#FC6151;\n"
"font: 8pt \"Verdana\";\n"
" border: None;\n"
"border-bottom-color: white;\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"background:#23272A;\n"
"selection-background-color: darkgray;\n"
"")
        self.label_event_login.setText("")
        self.label_event_login.setObjectName("label_event_login")
        self.gridLayout.addWidget(self.label_event_login, 13, 1, 1, 1)
        self.line_username_login = QtWidgets.QFrame(self.page_login)
        self.line_username_login.setStyleSheet("border: 2px solid #404EED ;")
        self.line_username_login.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_username_login.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_username_login.setObjectName("line_username_login")
        self.gridLayout.addWidget(self.line_username_login, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_login)
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_register)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_confirmPassword_register = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_confirmPassword_register.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_confirmPassword_register.setStyleSheet("color:#EEEEEE;\n"
"font: 15pt \"Verdana\";\n"
" border: None;\n"
"border-bottom-color: white;\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"background:#23272A;\n"
"selection-background-color: darkgray;\n"
"")
        self.lineEdit_confirmPassword_register.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_confirmPassword_register.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_confirmPassword_register.setObjectName("lineEdit_confirmPassword_register")
        self.gridLayout_6.addWidget(self.lineEdit_confirmPassword_register, 7, 1, 1, 1)
        self.line_confirmPassword_register = QtWidgets.QFrame(self.page_register)
        self.line_confirmPassword_register.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_confirmPassword_register.setStyleSheet("border: 2px solid #404EED ;")
        self.line_confirmPassword_register.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_confirmPassword_register.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_confirmPassword_register.setObjectName("line_confirmPassword_register")
        self.gridLayout_6.addWidget(self.line_confirmPassword_register, 8, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.page_register)
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#EEEEEE;\n"
"font: 30pt \"Bebas Neue\";\n"
"background:#23272A;\n"
"selection-background-color: darkgray;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 2, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem10, 2, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem11, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem12, 1, 1, 1, 1)
        self.lineEdit_password_register = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_password_register.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 169, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lineEdit_password_register.setPalette(palette)
        self.lineEdit_password_register.setStyleSheet("color:#EEEEEE;\n"
"font: 15pt \"Verdana\";\n"
" border: None;\n"
"border-bottom-color: white;\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"background:#23272A;\n"
"selection-background-color: darkgray;\n"
"")
        self.lineEdit_password_register.setInputMask("")
        self.lineEdit_password_register.setText("")
        self.lineEdit_password_register.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_register.setObjectName("lineEdit_password_register")
        self.gridLayout_6.addWidget(self.lineEdit_password_register, 5, 1, 1, 1)
        self.pushButton_signIn = QtWidgets.QPushButton(self.page_register)
        self.pushButton_signIn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_signIn.setStyleSheet("QPushButton\n"
"{\n"
"    color: #EEEEEE;\n"
"    font: 8pt \"Verdana\";\n"
"    text-decoration: underline;\n"
"    text-align:center;\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"    background-color:#23272A;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    color: #6671F0;\n"
"}")
        self.pushButton_signIn.setObjectName("pushButton_signIn")
        self.gridLayout_6.addWidget(self.pushButton_signIn, 12, 1, 1, 1)
        self.label_event_register = QtWidgets.QLabel(self.page_register)
        self.label_event_register.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_event_register.setAlignment(QtCore.Qt.AlignCenter)
        self.label_event_register.setStyleSheet("color:#FC6151;\n"
"font: 8pt \"Verdana\";\n"
" border: None;\n"
"border-bottom-color: white;\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"background:#23272A;\n"
"selection-background-color: darkgray;\n"
"")
        self.label_event_register.setText("")
        self.label_event_register.setObjectName("label_event_register")
        self.gridLayout_6.addWidget(self.label_event_register, 13, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem13, 10, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem14, 2, 2, 1, 1)
        self.pushButton_register = QtWidgets.QPushButton(self.page_register)
        self.pushButton_register.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_register.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_register.setStyleSheet("QPushButton\n"
"{\n"
"    color: #EEEEEE;\n"
"    font: 17pt \"Verdana\";\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"    background-color:#2C2F33;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#50555C;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color:#625C6A;\n"
"}")
        self.pushButton_register.setObjectName("pushButton_register")
        self.gridLayout_6.addWidget(self.pushButton_register, 11, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem15, 2, 0, 1, 1)
        self.lineEdit_username_register = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_username_register.setMinimumSize(QtCore.QSize(160, 40))
        self.lineEdit_username_register.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_username_register.setStyleSheet("color:#EEEEEE;\n"
"font: 15pt \"Verdana\";\n"
" border: None;\n"
"border-bottom-color: white;\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"background:#23272A;\n"
"selection-background-color: darkgray;\n"
"")
        self.lineEdit_username_register.setObjectName("lineEdit_username_register")
        self.gridLayout_6.addWidget(self.lineEdit_username_register, 2, 1, 1, 1)
        self.line_password_register = QtWidgets.QFrame(self.page_register)
        self.line_password_register.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_password_register.setStyleSheet("border: 2px solid #404EED ;")
        self.line_password_register.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_password_register.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_password_register.setObjectName("line_password_register")
        self.gridLayout_6.addWidget(self.line_password_register, 6, 1, 1, 1)
        self.line_username_register = QtWidgets.QFrame(self.page_register)
        self.line_username_register.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_username_register.setStyleSheet("border: 2px solid #404EED ;")
        self.line_username_register.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_username_register.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_username_register.setObjectName("line_username_register")
        self.gridLayout_6.addWidget(self.line_username_register, 3, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_register)
        self.gridLayout_3.addWidget(self.stackedWidget, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        connexion.setCentralWidget(self.centralwidget)

        self.retranslateUi(connexion)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(connexion)
        
        # Define the first page as Login
        self.stackedWidget.setCurrentWidget(self.page_login)
        
        # switch page
        self.pushButton_createAccount.clicked.connect(
            lambda: self.stackedWidget.setCurrentWidget(self.page_register))
        self.pushButton_signIn.clicked.connect(
            lambda: self.stackedWidget.setCurrentWidget(self.page_login))
            
        # Create user
        self.pushButton_register.clicked.connect(self.createAccount)
        
        # Connect user
        self.pushButton_login.clicked.connect(lambda: self.connectAccount(connexion))

        # login when enter is pressed
        self.lineEdit_username_login.returnPressed.connect(self.pushButton_login.click)
        self.lineEdit_password_login.returnPressed.connect(self.pushButton_login.click)


    def createAccount(self):
        print("===========TENTATIVE CREATION UTILISATEUR===========")
        # Connection to the database
        conn = sqlite3.connect('dataFile.db')
        cursor = conn.cursor()
        crypt = crypto()
    
        # Create a user table
        create_users_table = """CREATE TABLE IF NOT EXISTS
            users([user_id] INTEGER PRIMARY KEY,[username] TEXT, [password] TEXT, [private_key] TEXT, [public_key] TEXT)"""
        cursor.execute(create_users_table)
        conn.commit()
    
        # Create a contact table
        create_users_table = """CREATE TABLE IF NOT EXISTS
            contacts([contact_id] INTEGER PRIMARY KEY, [user_id] INTEGER, [contact_username] TEXT, [contact_onion] TEXT, [contact_publicKey] TEXT, FOREIGN KEY ([user_id]) REFERENCES users([user_id]))"""
        cursor.execute(create_users_table)
        conn.commit()
      
        # Recovers the data entered
        username = self.lineEdit_username_register.text()
        password = self.lineEdit_password_register.text()
        confirmPassword = self.lineEdit_confirmPassword_register.text()
        
        # Encrypted data entered
        encrypt_username = crypt.encrypted(password, username)
        encrypt_password = crypt.encrypted('', password)
    
        # Error : No passwd or username 
        if not username or not password:
            self.label_event_register.setStyleSheet("color:#FC6151;")
            self.label_event_register.setText("Fill in the form")
            print("===========CREATION ECHOUE : Password ou Username manquant===========")
            return

        # Error : Different passwords
        if password != confirmPassword:
            self.label_event_register.setStyleSheet("color:#FC6151;")
            self.label_event_register.setText("Password cannot be confirmed")
            print("===========CREATION ECHOUE : Password mal reconnu===========")
            return

        # Error : The user already exists
        for row in cursor.execute('SELECT username FROM users'):
            db_username = ''.join(row)
            decrypt_username = crypt.decrypted(password, db_username)
            if decrypt_username == username:
                self.label_event_register.setStyleSheet("color:#FC6151;")
                self.label_event_register.setText("The username is already taken")
                print("===========CREATION ECHOUE : Utilisateur deja existant===========")
                return

        #generating RSA key per
        keyPair = RSA.generate(2048)
        encrypted_pubKey = crypt.encrypted(password, keyPair.public_key().exportKey())
        encrypted_privKey = crypt.encrypted(password, keyPair.exportKey())

        # Add user
        cursor.execute(f"INSERT INTO users ( username, password, private_key, public_key) VALUES ('{encrypt_username}', '{encrypt_password}', '{encrypted_privKey}', '{encrypted_pubKey}')")
        conn.commit()

        self.label_event_register.setText("The account has been created")
        self.label_event_register.setStyleSheet("color:#27AE4E;")

        print("===========CREATION REUSSITE===========\n")


    def connectAccount(self, connexion):
        print("===========TENTATIVE CONNEXION UTILISATEUR===========")
        # Connection to the database
        conn = sqlite3.connect('dataFile.db')
        cursor = conn.cursor()
        crypt = crypto()
            
        # Recovers the data entered
        username = self.lineEdit_username_login.text()
        password = self.lineEdit_password_login.text()
 
        # Error : No passwd or username 
        if not username or not password:
            self.label_event_login.setStyleSheet("color:#FC6151;")
            self.label_event_login.setText("Fill in the form")
            print("===========CREATION ECHOUE : Password ou Username manquant===========")
            return
            
        # Verify user and passwd
        cursor.execute('SELECT * FROM users')
        rows = cursor.fetchall()
        i = 0
        for row in rows:
            db_username = ''.join(row[1])
            decrypt_username = crypt.decrypted(password, db_username)
            db_password = ''.join(row[2])
            decrypt_password = crypt.decrypted('', db_password)
        
            # Check if the user is logged in
            if ((decrypt_username != username) or (decrypt_password != password)):
                i = i+1
                if i == len(rows):
                    self.label_event_login.setStyleSheet("color:#FC6151;")
                    self.label_event_login.setText("Incorrect username or password")
                    print("===========CREATION ECHOUE : Utilisateur non trouvé===========")
                    return
 
            else:
                idUser = row[0]
                break

        # Connexion
        self.label_event_login.setText("You are logged in")
        self.label_event_login.setStyleSheet("color:#27AE4E;")
        print("===========CONNEXION REUSSITE===========")

        #################################################
        #affichage temp de l'id utilisateur
        #################################################
        cursor.execute(f'SELECT user_id, public_key FROM users')
        rows = cursor.fetchall()
        for row in rows:
            db_username = row[0]
            decrypt_username = crypt.decrypted(password, db_username)
            db_usernam = row[1]
            decrypt_usernam = crypt.decrypted(password, db_usernam)
            print(row[0])
            # delete contact
            if db_username == idUser:
                print(f"public key : {decrypt_usernam}")
                break
        #################################################

        # Close previous window
        connexion.hide()
        print("========================FERMETTURE CONNEXION.UI========================")
            
        # Open the new window
        self.open = window()
        self.open.openHomeUI(idUser, decrypt_password)


    def retranslateUi(self, connexion):
        _translate = QtCore.QCoreApplication.translate
        connexion.setWindowTitle(_translate("connexion", "Hermes - Secure messaging"))
        self.label_title.setText(_translate("connexion", "HERMES"))
        self.lineEdit_password_login.setPlaceholderText(_translate("connexion", "Password"))
        self.lineEdit_username_login.setPlaceholderText(_translate("connexion", "Username"))
        self.pushButton_login.setText(_translate("connexion", "Login"))
        self.pushButton_createAccount.setText(_translate("connexion", "Not registered yet ?\n"
"Create an Account"))
        self.lineEdit_confirmPassword_register.setPlaceholderText(_translate("connexion", "Confirm Password"))
        self.label_4.setText(_translate("connexion", "HERMES"))
        self.lineEdit_password_register.setPlaceholderText(_translate("connexion", "Password"))
        self.pushButton_signIn.setText(_translate("connexion", "Already have a account ?\n"
"Sign In"))
        self.pushButton_register.setText(_translate("connexion", "Register"))
        self.lineEdit_username_register.setPlaceholderText(_translate("connexion", "Username"))

class window(object):
    def openHomeUI(self, idUser, password):
        print("============TENTATIVE OUVERTURE HOME.UI============")
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_home()
        self.ui.setupUi(self.window, idUser, password)
        self.window.show()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    connexion = QtWidgets.QMainWindow()
    ui = Ui_connexion()
    ui.setupUi(connexion)
    connexion.show()
    sys.exit(app.exec_())
    
    